/**
 * 8 islands on the 5x6 odd-r hex grid.
 * Generated from solved colour paths and then scrambled, so every island is
 * guaranteed solvable and 3 stars are reachable within moveLimit * 0.6.
 * `basePorts` is the SOLVED orientation; `rotation` is the starting scramble.
 */
import type {Cell, Level} from './types';

export const ISLAND_COUNT = 8;

export const LEVELS: Level[] = [
  {
    id: 0,
    name: 'THE FIRST SPARK',
    moveLimit: 10,
    cells: [
      {row: 0, col: 3, kind: 'source', colour: 'cyan', basePorts: [3], rotation: 0},
      {row: 1, col: 1, kind: 'rune', colour: 'cyan', basePorts: [1, 2], rotation: 1},
      {row: 1, col: 2, kind: 'rune', colour: 'cyan', basePorts: [0, 4], rotation: 5},
      {row: 2, col: 2, kind: 'beacon', colour: 'cyan', basePorts: [5], rotation: 0},
      {row: 2, col: 3, kind: 'beacon', colour: 'cyan', basePorts: [3], rotation: 0},
      {row: 3, col: 1, kind: 'rune', colour: 'cyan', basePorts: [1, 2], rotation: 0},
      {row: 3, col: 2, kind: 'rune', colour: 'cyan', basePorts: [0, 4], rotation: 0},
      {row: 4, col: 2, kind: 'source', colour: 'cyan', basePorts: [5], rotation: 0},
    ],
  },
  {
    id: 1,
    name: 'AETHER FORGE',
    moveLimit: 12,
    cells: [
      {row: 0, col: 2, kind: 'beacon', colour: 'gold', basePorts: [1], rotation: 0},
      {row: 0, col: 3, kind: 'rune', colour: 'gold', basePorts: [3, 4], rotation: 1},
      {row: 0, col: 4, kind: 'source', colour: 'cyan', basePorts: [2], rotation: 0},
      {row: 1, col: 2, kind: 'rune', colour: 'gold', basePorts: [0, 3], rotation: 0},
      {row: 1, col: 4, kind: 'rune', colour: 'cyan', basePorts: [3, 5], rotation: 0},
      {row: 2, col: 1, kind: 'source', colour: 'gold', basePorts: [1], rotation: 0},
      {row: 2, col: 2, kind: 'rune', colour: 'gold', basePorts: [0, 4], rotation: 4},
      {row: 2, col: 4, kind: 'rune', colour: 'cyan', basePorts: [0, 3], rotation: 0},
      {row: 3, col: 3, kind: 'rune', colour: 'cyan', basePorts: [0, 2], rotation: 0},
      {row: 4, col: 4, kind: 'beacon', colour: 'cyan', basePorts: [5], rotation: 0},
    ],
  },
  {
    id: 2,
    name: 'STORMHOLD',
    moveLimit: 14,
    cells: [
      {row: 1, col: 4, kind: 'source', colour: 'cyan', basePorts: [3], rotation: 0},
      {row: 2, col: 2, kind: 'beacon', colour: 'cyan', basePorts: [1], rotation: 0},
      {row: 2, col: 3, kind: 'rune', colour: 'cyan', basePorts: [1, 2, 4], rotation: 0},
      {row: 2, col: 4, kind: 'rune', colour: 'cyan', basePorts: [0, 4], rotation: 0},
      {row: 3, col: 1, kind: 'source', colour: 'gold', basePorts: [2], rotation: 0},
      {row: 3, col: 2, kind: 'rune', colour: 'gold', basePorts: [1, 3], rotation: 0},
      {row: 3, col: 3, kind: 'beacon', colour: 'gold', basePorts: [4], rotation: 0},
      {row: 4, col: 2, kind: 'rune', colour: 'gold', basePorts: [0, 5], rotation: 0},
      {row: 5, col: 1, kind: 'beacon', colour: 'cyan', basePorts: [1], rotation: 0},
      {row: 5, col: 2, kind: 'rune', colour: 'cyan', basePorts: [1, 4], rotation: 3},
      {row: 5, col: 3, kind: 'rune', colour: 'cyan', basePorts: [1, 4], rotation: 2},
      {row: 5, col: 4, kind: 'source', colour: 'cyan', basePorts: [4], rotation: 0},
    ],
  },
  {
    id: 3,
    name: 'TITAN VEIN',
    moveLimit: 16,
    cells: [
      {row: 1, col: 3, kind: 'rune', colour: 'cyan', basePorts: [1, 3, 5], rotation: 0},
      {row: 1, col: 4, kind: 'rune', colour: 'cyan', basePorts: [3, 4], rotation: 0},
      {row: 2, col: 2, kind: 'beacon', colour: 'cyan', basePorts: [1], rotation: 0},
      {row: 2, col: 3, kind: 'rune', colour: 'cyan', basePorts: [0, 4], rotation: 1},
      {row: 2, col: 4, kind: 'source', colour: 'cyan', basePorts: [0], rotation: 0},
      {row: 3, col: 0, kind: 'rune', colour: 'cyan', basePorts: [1, 3], rotation: 0},
      {row: 3, col: 1, kind: 'source', colour: 'cyan', basePorts: [4], rotation: 0},
      {row: 3, col: 2, kind: 'rune', colour: 'gold', basePorts: [1, 2], rotation: 0},
      {row: 3, col: 3, kind: 'beacon', colour: 'gold', basePorts: [4], rotation: 0},
      {row: 4, col: 0, kind: 'rune', colour: 'cyan', basePorts: [0, 2], rotation: 0},
      {row: 4, col: 1, kind: 'source', colour: 'gold', basePorts: [1], rotation: 0},
      {row: 4, col: 2, kind: 'rune', colour: 'gold', basePorts: [1, 4], rotation: 2},
      {row: 4, col: 3, kind: 'rune', colour: 'gold', basePorts: [4, 5], rotation: 0},
      {row: 5, col: 0, kind: 'rune', colour: 'cyan', basePorts: [1, 5], rotation: 0},
      {row: 5, col: 1, kind: 'beacon', colour: 'cyan', basePorts: [4], rotation: 0},
    ],
  },
  {
    id: 4,
    name: 'CLOUD ANVIL',
    moveLimit: 18,
    cells: [
      {row: 0, col: 4, kind: 'source', colour: 'cyan', basePorts: [3], rotation: 0},
      {row: 1, col: 0, kind: 'source', colour: 'violet', basePorts: [3], rotation: 0},
      {row: 1, col: 3, kind: 'rune', colour: 'cyan', basePorts: [0, 1], rotation: 0},
      {row: 1, col: 4, kind: 'rune', colour: 'cyan', basePorts: [1, 3, 4], rotation: 0},
      {row: 2, col: 0, kind: 'rune', colour: 'violet', basePorts: [0, 1], rotation: 2},
      {row: 2, col: 1, kind: 'rune', colour: 'violet', basePorts: [1, 4], rotation: 0},
      {row: 2, col: 2, kind: 'rune', colour: 'violet', basePorts: [2, 4, 5], rotation: 0},
      {row: 2, col: 4, kind: 'rune', colour: 'cyan', basePorts: [0, 3], rotation: 0},
      {row: 3, col: 1, kind: 'source', colour: 'gold', basePorts: [2], rotation: 0},
      {row: 3, col: 2, kind: 'beacon', colour: 'violet', basePorts: [5], rotation: 0},
      {row: 3, col: 3, kind: 'beacon', colour: 'cyan', basePorts: [0], rotation: 0},
      {row: 4, col: 2, kind: 'rune', colour: 'gold', basePorts: [3, 5], rotation: 0},
      {row: 5, col: 1, kind: 'rune', colour: 'gold', basePorts: [0, 1], rotation: 0},
      {row: 5, col: 2, kind: 'rune', colour: 'gold', basePorts: [1, 4], rotation: 1},
      {row: 5, col: 3, kind: 'beacon', colour: 'gold', basePorts: [4], rotation: 0},
    ],
  },
  {
    id: 5,
    name: 'VIOLET GATE',
    moveLimit: 20,
    cells: [
      {row: 0, col: 0, kind: 'rune', colour: 'violet', basePorts: [1, 2, 5], rotation: 1},
      {row: 0, col: 1, kind: 'source', colour: 'violet', basePorts: [4], rotation: 0},
      {row: 1, col: 0, kind: 'rune', colour: 'violet', basePorts: [3, 5], rotation: 0},
      {row: 1, col: 1, kind: 'beacon', colour: 'gold', basePorts: [2], rotation: 0},
      {row: 1, col: 3, kind: 'source', colour: 'gold', basePorts: [2], rotation: 0},
      {row: 2, col: 0, kind: 'rune', colour: 'violet', basePorts: [0, 2], rotation: 0},
      {row: 2, col: 2, kind: 'rune', colour: 'gold', basePorts: [1, 5], rotation: 0},
      {row: 2, col: 3, kind: 'rune', colour: 'gold', basePorts: [1, 3, 4], rotation: 0},
      {row: 2, col: 4, kind: 'rune', colour: 'gold', basePorts: [4, 5], rotation: 1},
      {row: 3, col: 0, kind: 'beacon', colour: 'violet', basePorts: [5], rotation: 0},
      {row: 3, col: 1, kind: 'beacon', colour: 'cyan', basePorts: [3], rotation: 0},
      {row: 3, col: 2, kind: 'rune', colour: 'cyan', basePorts: [2, 3], rotation: 0},
      {row: 3, col: 3, kind: 'beacon', colour: 'cyan', basePorts: [3], rotation: 0},
      {row: 4, col: 0, kind: 'rune', colour: 'cyan', basePorts: [1, 2], rotation: 0},
      {row: 4, col: 1, kind: 'rune', colour: 'cyan', basePorts: [0, 4], rotation: 0},
      {row: 4, col: 2, kind: 'rune', colour: 'cyan', basePorts: [0, 2], rotation: 0},
      {row: 4, col: 3, kind: 'rune', colour: 'cyan', basePorts: [0, 5], rotation: 0},
      {row: 5, col: 0, kind: 'rune', colour: 'cyan', basePorts: [1, 5], rotation: 4},
      {row: 5, col: 1, kind: 'source', colour: 'cyan', basePorts: [4], rotation: 0},
      {row: 5, col: 2, kind: 'source', colour: 'cyan', basePorts: [5], rotation: 0},
    ],
  },
  {
    id: 6,
    name: 'THE LAST BEACON',
    moveLimit: 21,
    cells: [
      {row: 0, col: 0, kind: 'beacon', colour: 'violet', basePorts: [1], rotation: 0},
      {row: 0, col: 1, kind: 'rune', colour: 'violet', basePorts: [2, 4], rotation: 0},
      {row: 0, col: 2, kind: 'source', colour: 'violet', basePorts: [1], rotation: 0},
      {row: 0, col: 3, kind: 'rune', colour: 'violet', basePorts: [3, 4], rotation: 0},
      {row: 0, col: 4, kind: 'rune', colour: 'violet', basePorts: [0, 2, 3], rotation: 0},
      {row: 1, col: 0, kind: 'beacon', colour: 'gold', basePorts: [2], rotation: 0},
      {row: 1, col: 1, kind: 'rune', colour: 'violet', basePorts: [1, 2, 5], rotation: 0},
      {row: 1, col: 2, kind: 'rune', colour: 'violet', basePorts: [0, 4], rotation: 0},
      {row: 1, col: 3, kind: 'rune', colour: 'violet', basePorts: [0, 2], rotation: 1},
      {row: 1, col: 4, kind: 'source', colour: 'violet', basePorts: [5], rotation: 0},
      {row: 2, col: 0, kind: 'rune', colour: 'gold', basePorts: [1, 2], rotation: 0},
      {row: 2, col: 1, kind: 'rune', colour: 'gold', basePorts: [4, 5], rotation: 1},
      {row: 2, col: 2, kind: 'rune', colour: 'cyan', basePorts: [1, 3], rotation: 0},
      {row: 2, col: 3, kind: 'source', colour: 'cyan', basePorts: [4], rotation: 0},
      {row: 2, col: 4, kind: 'rune', colour: 'violet', basePorts: [2, 5], rotation: 4},
      {row: 3, col: 0, kind: 'rune', colour: 'gold', basePorts: [3, 5], rotation: 0},
      {row: 3, col: 1, kind: 'rune', colour: 'cyan', basePorts: [0, 2], rotation: 0},
      {row: 3, col: 3, kind: 'beacon', colour: 'violet', basePorts: [1], rotation: 0},
      {row: 3, col: 4, kind: 'rune', colour: 'violet', basePorts: [4, 5], rotation: 0},
      {row: 4, col: 0, kind: 'rune', colour: 'gold', basePorts: [0, 2], rotation: 0},
      {row: 4, col: 1, kind: 'beacon', colour: 'cyan', basePorts: [2], rotation: 0},
      {row: 4, col: 2, kind: 'rune', colour: 'cyan', basePorts: [3, 5], rotation: 0},
      {row: 5, col: 0, kind: 'source', colour: 'gold', basePorts: [5], rotation: 0},
      {row: 5, col: 1, kind: 'rune', colour: 'cyan', basePorts: [0, 5], rotation: 0},
    ],
  },
  {
    id: 7,
    name: 'OLYMPUS CROWN',
    moveLimit: 22,
    cells: [
      {row: 0, col: 1, kind: 'rune', colour: 'cyan', basePorts: [1, 2, 3], rotation: 0},
      {row: 0, col: 2, kind: 'rune', colour: 'cyan', basePorts: [1, 4], rotation: 0},
      {row: 0, col: 3, kind: 'rune', colour: 'cyan', basePorts: [1, 2, 4], rotation: 0},
      {row: 0, col: 4, kind: 'source', colour: 'cyan', basePorts: [4], rotation: 0},
      {row: 1, col: 0, kind: 'rune', colour: 'cyan', basePorts: [0, 1], rotation: 0},
      {row: 1, col: 1, kind: 'beacon', colour: 'cyan', basePorts: [4], rotation: 0},
      {row: 1, col: 3, kind: 'beacon', colour: 'gold', basePorts: [1], rotation: 0},
      {row: 1, col: 4, kind: 'rune', colour: 'gold', basePorts: [0, 3, 4], rotation: 2},
      {row: 2, col: 0, kind: 'rune', colour: 'gold', basePorts: [1, 2], rotation: 0},
      {row: 2, col: 1, kind: 'rune', colour: 'gold', basePorts: [2, 4], rotation: 0},
      {row: 2, col: 2, kind: 'source', colour: 'violet', basePorts: [2], rotation: 0},
      {row: 2, col: 4, kind: 'rune', colour: 'gold', basePorts: [0, 2], rotation: 0},
      {row: 3, col: 0, kind: 'rune', colour: 'gold', basePorts: [3, 5], rotation: 0},
      {row: 3, col: 1, kind: 'source', colour: 'gold', basePorts: [5], rotation: 0},
      {row: 3, col: 2, kind: 'rune', colour: 'violet', basePorts: [3, 5], rotation: 0},
      {row: 3, col: 3, kind: 'rune', colour: 'gold', basePorts: [1, 2], rotation: 0},
      {row: 3, col: 4, kind: 'rune', colour: 'gold', basePorts: [4, 5], rotation: 1},
      {row: 4, col: 0, kind: 'rune', colour: 'gold', basePorts: [0, 2], rotation: 0},
      {row: 4, col: 1, kind: 'rune', colour: 'violet', basePorts: [1, 2], rotation: 0},
      {row: 4, col: 2, kind: 'rune', colour: 'violet', basePorts: [0, 4], rotation: 0},
      {row: 4, col: 4, kind: 'source', colour: 'gold', basePorts: [5], rotation: 0},
      {row: 5, col: 0, kind: 'beacon', colour: 'gold', basePorts: [5], rotation: 0},
      {row: 5, col: 1, kind: 'rune', colour: 'violet', basePorts: [1, 5], rotation: 2},
      {row: 5, col: 2, kind: 'beacon', colour: 'violet', basePorts: [4], rotation: 0},
    ],
  },
];

export const beaconCountOf = (lv: Level): number =>
  lv.cells.filter((c: Cell) => c.kind === 'beacon').length;

export const levelMeta = (lv: Level): string =>
  '5x6 GRID . ' + beaconCountOf(lv) + ' BEACONS . ' + lv.moveLimit + ' MOVES';

export const getLevel = (index: number): Level =>
  LEVELS[Math.max(0, Math.min(LEVELS.length - 1, index))];
